extern const GeoLayout castle_grounds_area_1_geo[];
extern const GeoLayout castle_grounds_area_1[];
extern const Collision castle_grounds_area_1_collision[];
extern const MacroObject castle_grounds_area_1_macro_objs[];
extern u8 castle_grounds_dl_grass_ci4[];
extern u8 castle_grounds_dl_grass_pal_rgba16[];
extern u8 castle_grounds_dl_ground_ci8[];
extern u8 castle_grounds_dl_ground_pal_rgba16[];
extern u8 castle_grounds_dl_lava_ci8[];
extern u8 castle_grounds_dl_lava_pal_rgba16[];
extern u8 castle_grounds_dl_ground2_ci8[];
extern u8 castle_grounds_dl_ground2_pal_rgba16[];
extern Vtx castle_grounds_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx castle_grounds_dl_Level_Mesh_mesh_layer_1_vtx_0[4];
extern Gfx castle_grounds_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx castle_grounds_dl_Level_Mesh_mesh_layer_1_vtx_1[28];
extern Gfx castle_grounds_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx castle_grounds_dl_Level_Mesh_mesh_layer_1_vtx_2[8];
extern Gfx castle_grounds_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx castle_grounds_dl_Level_Mesh_mesh_layer_1_vtx_3[18];
extern Gfx castle_grounds_dl_Level_Mesh_mesh_layer_1_tri_3[];
extern Gfx mat_castle_grounds_dl_Grass_Example[];
extern Gfx mat_revert_castle_grounds_dl_Grass_Example[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_001[];
extern Gfx mat_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material_002[];
extern Gfx mat_castle_grounds_dl_f3dlite_material[];
extern Gfx mat_revert_castle_grounds_dl_f3dlite_material[];
extern Gfx castle_grounds_dl_Level_Mesh_mesh_layer_1[];
