extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern const GeoLayout bob_area_2_geo[];
extern const GeoLayout bob_area_2[];
extern const Collision bob_area_2_collision[];
extern const MacroObject bob_area_2_macro_objs[];
extern const GeoLayout bob_area_3_geo[];
extern const GeoLayout bob_area_3[];
extern const Collision bob_area_3_collision[];
extern const MacroObject bob_area_3_macro_objs[];
extern u8 bob_dl_cave_i8[];
extern u8 bob_dl_cave_ground_i4[];
extern u8 bob_dl_lava_ci8[];
extern u8 bob_dl_lava_pal_rgba16[];
extern u8 bob_dl_yummy_rocks_i8[];
extern u8 bob_dl_tubes_i8[];
extern u8 bob_dl_cave_ground_i8[];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_0[647];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_1[348];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_2[85];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Rocks_Visual_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Rocks_Visual_mesh_layer_1_vtx_0[801];
extern Gfx bob_dl_Rocks_Visual_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Rocks_Visual_mesh_layer_1_vtx_1[590];
extern Gfx bob_dl_Rocks_Visual_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_0[516];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_1[44];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_2[214];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_mesh_layer_1_vtx_3[881];
extern Gfx bob_dl_Cube_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_001_mesh_layer_1_vtx_0[384];
extern Gfx bob_dl_Cube_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_0[358];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_1[24];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_2[161];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Cube_002_mesh_layer_1_vtx_3[288];
extern Gfx bob_dl_Cube_002_mesh_layer_1_tri_3[];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_001_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_001_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_001_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_002_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_002_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_002_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_003_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_003_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_003_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_004_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_004_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_004_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_005_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_005_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_005_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_006_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_006_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_006_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_007_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_007_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_007_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_008_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_008_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_008_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_009_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_009_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_009_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_010_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_010_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_010_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Cylinder_011_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Cylinder_011_mesh_layer_1_vtx_0[50];
extern Gfx bob_dl_Cylinder_011_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_Walls[];
extern Gfx mat_revert_bob_dl_Walls[];
extern Gfx mat_bob_dl_Ground[];
extern Gfx mat_revert_bob_dl_Ground[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_revert_bob_dl_f3dlite_material_002[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx mat_bob_dl_f3dlite_material_004[];
extern Gfx mat_revert_bob_dl_f3dlite_material_004[];
extern Gfx mat_bob_dl_f3dlite_material_005[];
extern Gfx mat_revert_bob_dl_f3dlite_material_005[];
extern Gfx mat_bob_dl_f3dlite_material_006[];
extern Gfx mat_revert_bob_dl_f3dlite_material_006[];
extern Gfx mat_bob_dl_f3dlite_material_007[];
extern Gfx mat_revert_bob_dl_f3dlite_material_007[];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1[];
extern Gfx bob_dl_Rocks_Visual_mesh_layer_1[];
extern Gfx bob_dl_Cube_mesh_layer_1[];
extern Gfx bob_dl_Cube_001_mesh_layer_1[];
extern Gfx bob_dl_Cube_002_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_001_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_002_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_003_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_004_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_005_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_006_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_007_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_008_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_009_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_010_mesh_layer_1[];
extern Gfx bob_dl_Cylinder_011_mesh_layer_1[];
