extern const GeoLayout bob_area_1_geo[];
extern const GeoLayout bob_area_1[];
extern const Collision bob_area_1_collision[];
extern const MacroObject bob_area_1_macro_objs[];
extern u8 bob_dl_cave_i8[];
extern u8 bob_dl_cave_ground_i4[];
extern u8 bob_dl_lava_ci8[];
extern u8 bob_dl_lava_pal_rgba16[];
extern u8 bob_dl_yummy_rocks_i8[];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_0[419];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1_tri_0[];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_1[105];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1_tri_1[];
extern Vtx bob_dl_Level_Mesh_mesh_layer_1_vtx_2[49];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1_tri_2[];
extern Vtx bob_dl_Rocks_Visual_mesh_layer_1_vtx_cull[8];
extern Vtx bob_dl_Rocks_Visual_mesh_layer_1_vtx_0[407];
extern Gfx bob_dl_Rocks_Visual_mesh_layer_1_tri_0[];
extern Gfx mat_bob_dl_Walls[];
extern Gfx mat_revert_bob_dl_Walls[];
extern Gfx mat_bob_dl_Ground[];
extern Gfx mat_revert_bob_dl_Ground[];
extern Gfx mat_bob_dl_f3dlite_material_002[];
extern Gfx mat_revert_bob_dl_f3dlite_material_002[];
extern Gfx mat_bob_dl_f3dlite_material_001[];
extern Gfx mat_revert_bob_dl_f3dlite_material_001[];
extern Gfx bob_dl_Level_Mesh_mesh_layer_1[];
extern Gfx bob_dl_Rocks_Visual_mesh_layer_1[];
