extern const GeoLayout chill_flame_geo[];
extern u8 chill_flame_wood_i8[];
extern Vtx chill_flame_Cube_002_mesh_layer_5_vtx_cull[8];
extern Vtx chill_flame_Cube_002_mesh_layer_5_vtx_0[101];
extern Gfx chill_flame_Cube_002_mesh_layer_5_tri_0[];
extern Vtx chill_flame_Cube_002_mesh_layer_1_vtx_cull[8];
extern Vtx chill_flame_Cube_002_mesh_layer_1_vtx_0[24];
extern Gfx chill_flame_Cube_002_mesh_layer_1_tri_0[];
extern Gfx mat_chill_flame_f3dlite_material_004[];
extern Gfx mat_revert_chill_flame_f3dlite_material_004[];
extern Gfx mat_chill_flame_f3dlite_material_007[];
extern Gfx mat_revert_chill_flame_f3dlite_material_007[];
extern Gfx chill_flame_Cube_002_mesh_layer_5[];
extern Gfx chill_flame_Cube_002_mesh_layer_1[];
